In [1]:
from madmex.overlay.extractions import zonal_stats_xarray
import numpy as np
import datacube
from datacube.api import GridWorkflow
from madmex.wrappers import gwf_query
from madmex.models import Tag
import fiona
import pprint
import os
from madmex.models import Model
from madmex.overlay.conversions import rasterize_xarray
from madmex.util import chunk
import xarray as xr
import gc
from affine import Affine
from rasterio.features import rasterize
from itertools import chain, islice
from collections import OrderedDict


In [2]:
name_of_product = 's2_20m_fiona_test_2_2018'
resolution = (-10,10)
tilesize = (50020,50020)
origin = (2426720, 977160)
proj4 = '+proj=lcc +lat_1=17.5 +lat_2=29.5 +lat_0=12 +lon_0=-102 +x_0=2500000 +y_0=0 +a=6378137 +b=6378136.027241431 +units=m +no_defs'


In [3]:
gwf_kwargs = {'region': 'Jalisco', 'begin': '2018-01-01', 'end':'2018-12-31',
              'product': name_of_product,'resolution': resolution, 'origin': origin,
              'proj4': proj4, 'tilesize': tilesize}

In [4]:
iterable = gwf_query(**gwf_kwargs)

In [5]:
lista_iter = list(iterable)

In [6]:
[lista_iter[x][0] for x in range(0,len(lista_iter))]

[(28, -27),
 (28, -28),
 (30, -29),
 (30, -30),
 (28, -29),
 (28, -30),
 (29, -30),
 (30, -27),
 (29, -29),
 (30, -28),
 (29, -28),
 (29, -27)]

In [7]:
var = lista_iter[8]

In [8]:
sr_0 = GridWorkflow.load(var[1],dask_chunks={'x': 2000, 'y': 2000, 'time': 1})

In [9]:
sr_0

<xarray.Dataset>
Dimensions:     (time: 1, x: 5002, y: 5002)
Coordinates:
  * time        (time) datetime64[ns] 2018-07-02
  * y           (y) float64 1.026e+06 1.026e+06 ... 9.762e+05 9.761e+05
  * x           (x) float64 2.428e+06 2.428e+06 ... 2.478e+06 2.478e+06
Data variables:
    blue_mean   (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    green_mean  (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    red_mean    (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    re1_mean    (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    re2_mean    (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    re3_mean    (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    nir_mean    (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    swir1_mean  (time, y, x) int16 dask.array

In [10]:
s = fiona.open('s3://mysegmentation.shp')

In [11]:
geom_list = [x['geometry'] for x in s]


In [12]:
geom_list[1000]

{'type': 'Polygon',
 'coordinates': [[(2438580.0, 1021170.0),
   (2438620.0, 1021170.0),
   (2438620.0, 1021160.0),
   (2438660.0, 1021160.0),
   (2438660.0, 1021170.0),
   (2438740.0, 1021170.0),
   (2438740.0, 1021160.0),
   (2438750.0, 1021160.0),
   (2438750.0, 1020650.0),
   (2438740.0, 1020650.0),
   (2438250.0, 1020650.0),
   (2438250.0, 1021160.0),
   (2438360.0, 1021160.0),
   (2438360.0, 1021150.0),
   (2438400.0, 1021150.0),
   (2438400.0, 1021160.0),
   (2438500.0, 1021160.0),
   (2438500.0, 1021150.0),
   (2438520.0, 1021150.0),
   (2438520.0, 1021160.0),
   (2438530.0, 1021160.0),
   (2438530.0, 1021150.0),
   (2438540.0, 1021150.0),
   (2438540.0, 1021160.0),
   (2438570.0, 1021160.0),
   (2438580.0, 1021160.0),
   (2438580.0, 1021170.0)]]}

In [13]:
len(geom_list)

10000

In [14]:
aff = Affine(*list(sr_0.affine)[0:6])

In [15]:
dimensions_dataset = list(sr_0.coords)
list_dimensions = [x for x in dimensions_dataset if x != 'time']
lambda_function = lambda l_netcdf,l_test: l_netcdf[0] if l_netcdf[0] in l_test else l_netcdf[1]
xdim = lambda_function(list_dimensions,['x','longitude'])
ydim = lambda_function(list_dimensions,['y','latitude'])

In [16]:
iterable_zip = zip(geom_list, range(1, len(geom_list) + 1))

In [56]:
aff

Affine(10.0, 0.0, 2427740.0,
       0.0, -10.0, 1026160.0)

In [17]:
fc_raster = rasterize(iterable_zip, transform=aff,
                          out_shape=(sr_0.sizes[ydim], sr_0.sizes[xdim]),
                      dtype='float64', fill=np.nan)


In [18]:
fc_raster


array([[1.000e+00, 1.000e+00, 1.000e+00, ..., 8.100e+01, 8.100e+01,
        8.100e+01],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 8.100e+01, 8.100e+01,
        8.100e+01],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 8.100e+01, 8.100e+01,
        8.100e+01],
       ...,
       [9.901e+03, 9.901e+03, 9.901e+03, ..., 9.992e+03, 9.992e+03,
        9.992e+03],
       [9.901e+03, 9.901e+03, 9.901e+03, ..., 9.992e+03, 9.992e+03,
        9.992e+03],
       [9.901e+03, 9.901e+03, 9.901e+03, ..., 9.992e+03, 9.992e+03,
        9.992e+03]])

In [37]:
fc_raster[0]

array([ 1.,  1.,  1., ..., 81., 81., 81.])

In [38]:
fc_raster.shape

(5002, 5002)

In [39]:
fc_raster[1]

array([ 1.,  1.,  1., ..., 81., 81., 81.])

In [53]:
fc_raster[50]

array([ 1.,  1.,  1., ..., 81., 81., 81.])

In [52]:
fc_raster[51]

array([108., 108., 108., ..., 171., 171., 171.])

In [55]:
fc_raster[70]

array([108., 108., 108., ..., 171., 171., 171.])

In [54]:
fc_raster[101]

array([204., 204., 204., ..., 277., 277., 277.])

In [45]:
fc_raster[5000]

array([9901., 9901., 9901., ..., 9992., 9992., 9992.])

In [44]:
fc_raster[5001]

array([9901., 9901., 9901., ..., 9992., 9992., 9992.])

In [19]:
xr_arr = xr.DataArray(fc_raster, dims=[ydim, xdim], name='features_id')

In [20]:
xr_arr

<xarray.DataArray 'features_id' (y: 5002, x: 5002)>
array([[1.000e+00, 1.000e+00, 1.000e+00, ..., 8.100e+01, 8.100e+01, 8.100e+01],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 8.100e+01, 8.100e+01, 8.100e+01],
       [1.000e+00, 1.000e+00, 1.000e+00, ..., 8.100e+01, 8.100e+01, 8.100e+01],
       ...,
       [9.901e+03, 9.901e+03, 9.901e+03, ..., 9.992e+03, 9.992e+03, 9.992e+03],
       [9.901e+03, 9.901e+03, 9.901e+03, ..., 9.992e+03, 9.992e+03, 9.992e+03],
       [9.901e+03, 9.901e+03, 9.901e+03, ..., 9.992e+03, 9.992e+03, 9.992e+03]])
Dimensions without coordinates: y, x

In [21]:
combined = xr.merge([xr_arr, sr_0])

In [22]:
combined

<xarray.Dataset>
Dimensions:      (time: 1, x: 5002, y: 5002)
Coordinates:
  * x            (x) float64 2.428e+06 2.428e+06 ... 2.478e+06 2.478e+06
  * y            (y) float64 1.026e+06 1.026e+06 ... 9.762e+05 9.761e+05
  * time         (time) datetime64[ns] 2018-07-02
Data variables:
    features_id  (y, x) float64 1.0 1.0 1.0 ... 9.992e+03 9.992e+03 9.992e+03
    blue_mean    (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    green_mean   (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    red_mean     (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    re1_mean     (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    re2_mean     (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    re3_mean     (time, y, x) int16 dask.array<shape=(1, 5002, 5002), chunksize=(1, 2000, 2000)>
    nir_mean     (time, y, x) int16 dask.array<shape=

In [23]:
combined = combined.stack(z=(xdim, ydim))

In [24]:
combined

<xarray.Dataset>
Dimensions:      (time: 1, z: 25020004)
Coordinates:
  * time         (time) datetime64[ns] 2018-07-02
  * z            (z) MultiIndex
  - x            (z) float64 2.428e+06 2.428e+06 ... 2.428e+06 2.428e+06
  - y            (z) float64 1.026e+06 1.026e+06 ... 1.026e+06 1.026e+06
Data variables:
    features_id  (z) float64 1.0 1.0 1.0 1.0 ... 9.992e+03 9.992e+03 9.992e+03
    blue_mean    (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    green_mean   (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    red_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re1_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re2_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re3_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    nir_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksiz

In [25]:
combined=combined.reset_index('z')

In [26]:
combined

<xarray.Dataset>
Dimensions:      (time: 1, z: 25020004)
Coordinates:
  * time         (time) datetime64[ns] 2018-07-02
    x            (z) float64 2.428e+06 2.428e+06 ... 2.478e+06 2.478e+06
    y            (z) float64 1.026e+06 1.026e+06 ... 9.762e+05 9.761e+05
Dimensions without coordinates: z
Data variables:
    features_id  (z) float64 1.0 1.0 1.0 1.0 ... 9.992e+03 9.992e+03 9.992e+03
    blue_mean    (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    green_mean   (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    red_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re1_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re2_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re3_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    nir_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunks

In [27]:
combined=combined.drop([xdim,ydim])

In [28]:
combined

<xarray.Dataset>
Dimensions:      (time: 1, z: 25020004)
Coordinates:
  * time         (time) datetime64[ns] 2018-07-02
Dimensions without coordinates: z
Data variables:
    features_id  (z) float64 1.0 1.0 1.0 1.0 ... 9.992e+03 9.992e+03 9.992e+03
    blue_mean    (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    green_mean   (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    red_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re1_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re2_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re3_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    nir_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    swir1_mean   (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    swir2_mean   (time, z) int16 dask.a

In [42]:
#combined = combined.stack(z=(xdim, ydim)).reset_index('z').drop([xdim, ydim])

In [43]:
combined

<xarray.Dataset>
Dimensions:      (time: 1, z: 25020004)
Coordinates:
  * time         (time) datetime64[ns] 2018-07-02
Dimensions without coordinates: z
Data variables:
    features_id  (z) float64 1.0 1.0 1.0 1.0 ... 9.992e+03 9.992e+03 9.992e+03
    blue_mean    (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    green_mean   (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    red_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re1_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re2_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re3_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    nir_mean     (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    swir1_mean   (time, z) int16 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    swir2_mean   (time, z) int16 dask.a

In [29]:
combined = combined.where(np.isfinite(combined['features_id']), drop=True)

In [30]:
combined

<xarray.Dataset>
Dimensions:      (time: 1, z: 25020004)
Coordinates:
  * time         (time) datetime64[ns] 2018-07-02
Dimensions without coordinates: z
Data variables:
    features_id  (z) float64 1.0 1.0 1.0 1.0 ... 9.992e+03 9.992e+03 9.992e+03
    blue_mean    (time, z) float64 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    green_mean   (time, z) float64 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    red_mean     (time, z) float64 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re1_mean     (time, z) float64 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re2_mean     (time, z) float64 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    re3_mean     (time, z) float64 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    nir_mean     (time, z) float64 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    swir1_mean   (time, z) float64 dask.array<shape=(1, 25020004), chunksize=(1, 3331332)>
    swir2_mean   (time,

In [31]:
df = combined.to_dataframe()

In [32]:
df

features_id  blue_mean  green_mean  red_mean  re1_mean  \
time       z                                                                  
2018-07-02 0                 1.0      607.0       832.0    1106.0    1299.0   
           1                 1.0      607.0       832.0    1106.0    1299.0   
           2                 1.0      531.0       784.0     972.0    1160.0   
           3                 1.0      531.0       784.0     972.0    1160.0   
           4                 1.0      578.0       830.0    1025.0    1293.0   
           5                 1.0      578.0       830.0    1025.0    1293.0   
           6                 1.0      605.0       861.0    1101.0    1361.0   
           7                 1.0      605.0       861.0    1101.0    1361.0   
           8                 1.0      574.0       806.0    1052.0    1271.0   
           9                 1.0      574.0       806.0    1052.0    1271.0   
           10                1.0      454.0       632.0     823.0    1053.0   
           11                1.0      454.0       632.0     823.0    1053.0   
           12                1.0      461.0       592.0     783.0     916.0   
           13                1.0      461.0       592.0     783.0     916.0   
           14                1.0      436.0       586.0     756.0     852.0   
           15                1.0      436.0       586.0     756.0     852.0   
           16                1.0      399.0       511.0     689.0     800.0   
           17                1.0      399.0       511.0     689.0     800.0   
           18                1.0      451.0       587.0     773.0     870.0   
           19                1.0      451.0       587.0     773.0     870.0   
           20                1.0      527.0       687.0     884.0    1064.0   
           21                1.0      527.0       687.0     884.0    1064.0   
           22                1.0      578.0       742.0    1001.0    1205.0   
           23                1.0      578.0       742.0    1001.0    1205.0   
           24                1.0      548.0       769.0    1076.0    1270.0   
           25                1.0      548.0       769.0    1076.0    1270.0   
           26                1.0      563.0       742.0     947.0    1186.0   
           27                1.0      563.0       742.0     947.0    1186.0   
           28                1.0      721.0       944.0    1264.0    1386.0   
           29                1.0      721.0       944.0    1264.0    1386.0   
...                          ...        ...         ...       ...       ...   
           25019974       9992.0      315.0       529.0     668.0    1017.0   
           25019975       9992.0      315.0       529.0     668.0    1017.0   
           25019976       9992.0      307.0       528.0     632.0     915.0   
           25019977       9992.0      307.0       528.0     632.0     915.0   
           25019978       9992.0      472.0       723.0     944.0    1220.0   
           25019979       9992.0      472.0       723.0     944.0    1220.0   
           25019980       9992.0      565.0       831.0    1135.0    1352.0   
           25019981       9992.0      565.0       831.0    1135.0    1352.0   
           25019982       9992.0      492.0       739.0     989.0    1290.0   
           25019983       9992.0      492.0       739.0     989.0    1290.0   
           25019984       9992.0      521.0       766.0    1024.0    1227.0   
           25019985       9992.0      521.0       766.0    1024.0    1227.0   
           25019986       9992.0      389.0       626.0     803.0    1180.0   
           25019987       9992.0      389.0       626.0     803.0    1180.0   
           25019988       9992.0      401.0       629.0     831.0    1008.0   
           25019989       9992.0      401.0       629.0     831.0    1008.0   
           25019990       9992.0      286.0       495.0     609.0     930.0   
           25019991       9992.0      286.0       495.0     609.0     9

In [34]:
var_list = list(sr_0.data_vars)
categorical_variables = []
agg_list = [(k, 'mean') if k not in categorical_variables else (k, 'first') for k in var_list]
agg_ordered_dict = OrderedDict(agg_list)

In [35]:
df = df.groupby('features_id').agg(agg_ordered_dict)

In [36]:
df

blue_mean   green_mean     red_mean     re1_mean     re2_mean  \
features_id                                                                    
1.0           472.582853   654.138793   840.590542  1026.809304  1171.425606   
2.0           453.378039   639.167451   823.304706  1025.450588  1208.492157   
3.0           518.131373   728.714510   973.007451  1181.454118  1362.098039   
4.0           370.210588   526.901569   688.634118   862.292549  1035.648235   
5.0           488.187843   672.152549   856.782353  1061.650588  1261.118039   
6.0           453.423922   623.374510   764.794118   977.790588  1216.125098   
7.0           480.037647   660.080000   857.830980  1068.420784  1259.284314   
8.0           425.009412   585.106275   748.577255   951.054902  1148.786275   
9.0           443.653333   607.083137   718.105098   948.784314  1235.028235   
10.0          558.476863   776.745098   977.142353  1228.802745  1538.421569   
11.0          743.318789  1035.711871  1329.061321  1621.772013  1938.693003   
12.0          531.538462   787.583203  1074.450157  1348.144035  1644.495290   
13.0          524.743984   752.348323   946.751874  1207.388166  1549.027219   
14.0          656.209934   930.381063  1291.481568  1520.791618  1675.230501   
15.0          419.683702   606.821328   770.772233  1000.315091  1295.176258   
16.0          476.185882   667.763137   879.763529  1089.413725  1293.266667   
17.0          546.048627   748.501569   956.499216  1194.016863  1453.544314   
18.0          513.338601   703.293955   854.646780  1132.116160  1458.033979   
19.0          708.616078   974.276471  1243.393333  1526.681176  1924.507843   
20.0          706.690411   990.237573  1242.497065  1551.655969  1918.465753   
21.0          785.706275  1097.799216  1438.356471  1739.944314  2024.250588   
22.0          666.896863   926.723922  1194.396863  1478.139216  1773.701961   
23.0          528.470588   752.512941   978.838431  1239.732157  1524.285882   
24.0          560.286444   778.823576  1020.282122  1259.688802  1460.778782   
25.0          877.990122  1148.636507  1508.393915  1776.772817  1971.273805   
26.0          443.170020   644.475345   806.089941  1064.041026  1374.625641   
27.0          351.498400   532.396800   595.451200   876.067200  1297.740800   
28.0          348.580747   525.522593   579.713556   872.096660  1341.736346   
29.0          415.852291   600.111374   745.551343   984.828989  1255.549763   
30.0          864.114207  1149.379906  1505.438383  1794.034144  2018.164050   
...                  ...          ...          ...          ...          ...   
9971.0        797.540508  1135.192613  1605.858618  1914.605639  2191.530183   
9972.0        648.763776  1003.089403  1463.314066  1749.049326  1947.604624   
9973.0        385.341880   617.188034   947.891331  1199.425722  1517.329263   
9974.0        510.330395   908.854725   789.796544  1045.656559   555.474612   
9975.0        669.494898   935.583987  1237.034929  1541.602433  1942.899922   
9976.0        377.751176   618.932602   965.721003  1220.409483  1526.155956   
9977.0        681.212733  1069.635870  1616.215062  1916.404891  2096.049689   
9978.0        508.066484   764.500978  1078.463434  1366.948377  1655.890497   
9979.0        360.705835   589.082334   825.798961  1119.068745  1562.317346   
9980.0        548.445316   912.506860   873.655429  1091.700902   720.163073   
9981.0        501.854567   782.869071  1100.760486  1403.248922  1879.325363   
9982.0        702.535868   931.503724  1142.064289  1468.397099  1825.392787   
9983.0        492.464400   778.963600  1267.166400  1509.127200  1714.475200   
9984.0        540.798300   975.050618   814.615147  1174.416151   801.149536   
9985.0        443.500000   715.333987  1044.925039  1345.387363  1764.264521   
9986.0        540.485758   818.167821  1163.918784  1449.586990  1889.354119   
9987.0        606.607393   933.897276   987.396109  1144.723346   842.736576   
9988.0        6

In [57]:
ids = list(df.index.values.astype('uint32') - 1)

In [67]:
len(ids)

10000

In [76]:
y=np.array([s[x]['properties']['id'] for x in range(0,len(ids))])

In [77]:
y

array([   0,    1,    2, ..., 9979, 9904, 9969])

In [78]:
y.shape

(10000,)

In [66]:
s[1]['properties']['id']

1

In [79]:
s.close()

In [32]:
ids_list = [x['id'] for x in s]

In [34]:
len(ids_list)

10000

In [35]:
iterable_zip2 = zip(geom_list, ids_list)

In [37]:
fc_raster = rasterize(iterable_zip2, transform=aff,
                          out_shape=(sr_0.sizes[ydim], sr_0.sizes[xdim]),
                      dtype='float64', fill=np.nan)

TypeError: cannot perform reduce with flexible type