In [1]:
from madmex.wrappers import gwf_query
import datacube
from datetime import datetime
import xarray as xr
from madmex.util.xarray import to_float, to_int
from datacube.api import GridWorkflow

In [2]:
dc = datacube.Datacube()


In [85]:
options = {}
name_of_product = 'recipe_s2_10m_scl_Veracruz_sample_2019_2'
#name_of_product = 'l7_oax_50km_no_gaps_recipe_0405'
#x = (-96.93511962890624, -96.536865234375)
#y = (16.909683615558635, 17.19852235364461)
x = (-97.833251953125, -96.6522216796875)
y = (19.756364230752375, 20.648205934292623)
options['lat'] = y
options['long'] = x
options['region'] = None
options['begin'] = "2019-01-1"
options['end'] = "2019-12-1"
band_list = None

In [86]:
gwf_kwargs = { k: options[k] for k in ['lat', 'long', 'region', 'begin', 'end']}
gwf_kwargs.update(product=name_of_product)
iterable = gwf_query(**gwf_kwargs)

In [87]:
gwf_kwargs

{'lat': (19.756364230752375, 20.648205934292623),
 'long': (-97.833251953125, -96.6522216796875),
 'region': None,
 'begin': '2019-01-1',
 'end': '2019-12-1',
 'product': 'recipe_s2_10m_scl_Veracruz_sample_2019_2'}

In [88]:
len(iterable)

7

In [89]:
list(iterable)[3][0]

(40, -31)

In [90]:
tile = list(iterable)[3][1]

In [91]:
tile

Tile<sources=<xarray.DataArray (time: 1)>
array([(Dataset <id=2d6ff737-665c-5088-b6c9-1adb5ef2e01a type=recipe_s2_10m_scl_Veracruz_sample_2019_2 location=file://shared_volume/datacube/datacube_ingest/recipes/recipe_s2_10m_scl_Veracruz_sample_2019_2/s2_10m_scl_ndvi_mean_001_40_-31_2019-07-02.nc>,)],
      dtype=object)
Coordinates:
  * time     (time) datetime64[ns] 2019-07-02,
	geobox=GeoBox(5002, 5002, Affine(10.0, 0.0, 2977960.0,
       0.0, -10.0, 926120.0), PROJCS["unnamed",GEOGCS["WGS 84",DATUM["unknown",SPHEROID["WGS84",6378137,6556752.3141]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",17.5],PARAMETER["standard_parallel_2",29.5],PARAMETER["latitude_of_origin",12],PARAMETER["central_meridian",-102],PARAMETER["false_easting",2500000],PARAMETER["false_northing",0]])>

In [92]:
geoarray = GridWorkflow.load(tile, measurements=band_list)

In [93]:
geoarray

<xarray.Dataset>
Dimensions:    (time: 1, x: 5002, y: 5002)
Coordinates:
  * time       (time) datetime64[ns] 2019-07-02
  * y          (y) float64 9.261e+05 9.261e+05 9.261e+05 ... 8.761e+05 8.761e+05
  * x          (x) float64 2.978e+06 2.978e+06 2.978e+06 ... 3.028e+06 3.028e+06
Data variables:
    ndvi_mean  (time, y, x) int16 7138 7310 7233 7356 ... 6553 6581 6733 6544
Attributes:
    crs:      PROJCS["unnamed",GEOGCS["WGS 84",DATUM["unknown",SPHEROID["WGS8...

In [94]:
name_of_product = 's2_l2a_10m_scl_mexico'

In [107]:
gwf_kwargs = { k: options[k] for k in ['lat', 'long', 'region', 'begin', 'end']}
gwf_kwargs.update(product=name_of_product)
iterable = gwf_query(**gwf_kwargs, view=True)
#iterable = GridWorkflow.list_tiles(**gwf_kwargs)

In [108]:
#ds = dc.load(name_of_product, time=(datetime(2019, 1, 1), datetime(2019, 12, 1)),x=x,y=y)


In [110]:
list(iterable)[3]

((40, -31), Tile<sources=<xarray.DataArray (time: 35)>
 array([(Dataset <id=25e6c241-44e2-4771-94e0-7f5784d2386d type=s2_l2a_10m_scl_mexico location=file:///shared_volume/datacube/datacube_ingest/s2_l2a_10m_scl_s3/mexico/s2_l2a_10m_scl_s3_40_-31_20190107171802000000.nc>,),
        (Dataset <id=c5d68368-e7c6-47da-902a-e4751972abb6 type=s2_l2a_10m_scl_mexico location=file:///shared_volume/datacube/datacube_ingest/s2_l2a_10m_scl_s3/mexico/s2_l2a_10m_scl_s3_40_-31_20190107171817000000.nc>,),
        (Dataset <id=bcafb379-52f8-4521-84c1-f75c9a01d5ce type=s2_l2a_10m_scl_mexico location=file:///shared_volume/datacube/datacube_ingest/s2_l2a_10m_scl_s3/mexico/s2_l2a_10m_scl_s3_40_-31_20190124170823000000.nc>,),
        (Dataset <id=9b65c170-92d6-4615-873d-eebb7f21c3e8 type=s2_l2a_10m_scl_mexico location=file:///shared_volume/datacube/datacube_ingest/s2_l2a_10m_scl_s3/mexico/s2_l2a_10m_scl_s3_40_-31_20190203170806000000.nc>,),
        (Dataset <id=da83cb16-9243-4461-ae15-25263255becf type=s2_l2a

In [111]:
tile = list(iterable)[3]

In [120]:
sr_0 = xr.merge([GridWorkflow.load(tile[1], dask_chunks={'x': 1000, 'y': 1000},
                                   measurements=['red','nir','pixel_qa'])])

In [121]:
sr_0

<xarray.Dataset>
Dimensions:   (time: 35, x: 5002, y: 5002)
Coordinates:
  * time      (time) datetime64[ns] 2019-01-07T17:18:02 ... 2019-08-02T17:08:28.560000
  * y         (y) float64 9.261e+05 9.261e+05 9.261e+05 ... 8.761e+05 8.761e+05
  * x         (x) float64 2.978e+06 2.978e+06 2.978e+06 ... 3.028e+06 3.028e+06
Data variables:
    red       (time, y, x) uint16 dask.array<shape=(35, 5002, 5002), chunksize=(35, 1000, 1000)>
    nir       (time, y, x) uint16 dask.array<shape=(35, 5002, 5002), chunksize=(35, 1000, 1000)>
    pixel_qa  (time, y, x) uint16 dask.array<shape=(35, 5002, 5002), chunksize=(35, 1000, 1000)>

In [122]:
sr_0['time']

<xarray.DataArray 'time' (time: 35)>
array(['2019-01-07T17:18:02.000000000', '2019-01-07T17:18:17.000000000',
       '2019-01-24T17:08:23.000000000', '2019-02-03T17:08:06.000000000',
       '2019-02-03T17:08:20.000000000', '2019-02-06T17:18:04.000000000',
       '2019-02-06T17:18:19.000000000', '2019-02-13T17:08:09.000000000',
       '2019-02-16T17:17:57.000000000', '2019-02-16T17:18:04.000000000',
       '2019-02-16T17:18:18.000000000', '2019-02-26T17:18:03.100000000',
       '2019-02-26T17:18:11.490000000', '2019-02-26T17:18:11.600000000',
       '2019-02-26T17:18:17.820000000', '2019-03-08T17:18:02.220000000',
       '2019-03-08T17:18:16.760000000', '2019-03-18T17:18:19.570000000',
       '2019-03-25T17:08:08.420000000', '2019-03-25T17:08:23.000000000',
       '2019-03-28T17:18:07.370000000', '2019-04-04T17:08:10.250000000',
       '2019-04-04T17:08:13.240000000', '2019-04-04T17:08:24.830000000',
       '2019-04-14T17:08:11.770000000', '2019-04-27T17:18:25.770000000',
       '2019-0

In [ ]:
20190107T170701_T14QPG
20190107T170701_T14QPH
20190124T165601_T14QPG
20190203T165511_T14QQG
20190203T165511_T14QQH
20190206T170501_T14QPG
20190206T170501_T14QPH
20190213T165411_T14QPH
20190216T170401_T14QPG
20190216T170401_T14QPH
20190226T170251_T14QPG
20190226T170251_T14QPH
20190308T170131_T14QPG
20190308T170131_T14QPH
20190318T170021_T14QPG
20190325T164931_T14QQG
20190325T164931_T14QQH
20190328T170201_T14QPH
20190404T165211_T14QPH
20190404T165211_T14QQG
20190404T165211_T14QQH
20190414T164901_T14QQH
20190427T165901_T14QPG
20190504T164901_T14QPG
20190504T164901_T14QQG
20190504T164901_T14QQH
20190524T164901_T14QQG
20190524T164901_T14QQH
20190703T164901_T14QQH
20190723T164901_T14QQG
20190723T164901_T14QQH
20190802T164901_T14QQG
20190802T164901_T14QQH
20190812T164901_T14QQG
20190812T164901_T14QQH
20190822T164901_T14QQG
20190901T164901_T14QQG

# 5 nov 2019

In [1]:
import numpy as np
import xarray as xr
from datetime import datetime
import datetime as dt
import glob

## 1. Obtener un xarray dataset. Debe ser similar a datos preprocesados de algún satélite: landsat o sentinel2. Ahora se utilizan datos que no fueron registrados en la db del datacube

# 1a Datos aleatorios

In [2]:
date_list = [datetime(2019, 1, 1) + dt.timedelta(delta) for delta in range(6)]

xarr1 = xr.DataArray(np.random.rand(1667,1667), dims=['y', 'x'], coords = {'time':date_list[0]})
np.random.seed(1979)
xarr2 = xr.DataArray(np.random.rand(1667,1667), dims=['y', 'x'], coords = {'time':date_list[1]})
np.random.seed(1989)
xarr3 = xr.DataArray(np.random.rand(1667,1667), dims=['y', 'x'], coords = {'time':date_list[2]})
np.random.seed(1999)
xarr4 = xr.DataArray(np.random.rand(1667,1667), dims=['y', 'x'], coords = {'time':date_list[3]})
np.random.seed(2009)
xarr5 = xr.DataArray(np.random.rand(1667,1667), dims=['y', 'x'], coords = {'time':date_list[4]})
np.random.seed(2019)
xarr6 = xr.DataArray(np.random.rand(1667,1667), dims=['y', 'x'], coords = {'time':date_list[5]})

xarr_band = xr.concat([xarr1,xarr2,xarr3,xarr4,xarr5,xarr6],dim='time')


xset = xr.Dataset({})

xset['blue'] = xarr_band
xset['red'] = 3.0*xarr_band
xset['green'] = 4.0*xarr_band
xset['nir'] = 5.0*xarr_band

print(xset)

<xarray.Dataset>
Dimensions:  (time: 6, x: 1667, y: 1667)
Coordinates:
  * time     (time) datetime64[ns] 2019-01-01 2019-01-02 ... 2019-01-06
Dimensions without coordinates: x, y
Data variables:
    blue     (time, y, x) float64 0.1586 0.7531 0.5985 ... 0.697 0.4095 0.2409
    red      (time, y, x) float64 0.4759 2.259 1.795 ... 2.091 1.229 0.7228
    green    (time, y, x) float64 0.6345 3.013 2.394 ... 2.788 1.638 0.9637
    nir      (time, y, x) float64 0.7931 3.766 2.992 4.87 ... 3.485 2.048 1.205


In [3]:
xset.nir

<xarray.DataArray 'nir' (time: 6, y: 1667, x: 1667)>
array([[[0.79310097, 3.76573765, 2.99230151, ..., 4.81752841,
         0.81864667, 4.08922666],
        [0.6297229 , 1.29656436, 1.22011802, ..., 0.90862568,
         0.44143281, 3.53951982],
        [4.41965745, 3.09620681, 1.23023163, ..., 3.79928186,
         3.30057094, 3.85231879],
        ...,
        [4.81106065, 1.52859097, 1.9801649 , ..., 4.12418323,
         2.8329167 , 4.91740377],
        [3.77444585, 1.16372452, 0.78441729, ..., 4.13369406,
         2.96258145, 0.64909775],
        [4.51757662, 2.55034372, 1.78333456, ..., 4.47653154,
         0.44429385, 3.61220433]],

       [[4.89104657, 3.75004763, 2.79817224, ..., 0.75966699,
         1.44583475, 0.15554227],
        [3.65241815, 0.24847929, 2.76293383, ..., 1.26419752,
         4.96286429, 2.25320543],
        [1.78361284, 0.55423628, 1.90054749, ..., 3.57628016,
         4.53157544, 4.21729651],
        ...,
        [3.78159852, 1.70629966, 0.62215317, ..., 1.625

In [4]:
xset.red

<xarray.DataArray 'red' (time: 6, y: 1667, x: 1667)>
array([[[0.47586058, 2.25944259, 1.79538091, ..., 2.89051705,
         0.491188  , 2.453536  ],
        [0.37783374, 0.77793862, 0.73207081, ..., 0.54517541,
         0.26485968, 2.12371189],
        [2.65179447, 1.85772409, 0.73813898, ..., 2.27956912,
         1.98034256, 2.31139127],
        ...,
        [2.88663639, 0.91715458, 1.18809894, ..., 2.47450994,
         1.69975002, 2.95044226],
        [2.26466751, 0.69823471, 0.47065037, ..., 2.48021643,
         1.77754887, 0.38945865],
        [2.71054597, 1.53020623, 1.07000074, ..., 2.68591892,
         0.26657631, 2.1673226 ]],

       [[2.93462794, 2.25002858, 1.67890334, ..., 0.45580019,
         0.86750085, 0.09332536],
        [2.19145089, 0.14908758, 1.6577603 , ..., 0.75851851,
         2.97771857, 1.35192326],
        [1.07016771, 0.33254177, 1.14032849, ..., 2.1457681 ,
         2.71894527, 2.53037791],
        ...,
        [2.26895911, 1.0237798 , 0.3732919 , ..., 0.975

## 2 Calcular ndvi por ventana de tiempos para cada banda

http://xarray.pydata.org/en/stable/generated/xarray.DataArray.rolling.html#xarray.DataArray.rolling

In [5]:
time_window = 2

In [6]:
#ejemplo de cálculo de promedio en ventana de tiempo definida con time_window
xset.blue.rolling(time=time_window).mean().dropna('time')

<xarray.DataArray (time: 5, y: 1667, x: 1667)>
array([[[0.56841475, 0.75157853, 0.57904738, ..., 0.55771954,
         0.22644814, 0.42447689],
        [0.42821411, 0.15450437, 0.39830518, ..., 0.21728232,
         0.54042971, 0.57927253],
        [0.62032703, 0.36504431, 0.31307791, ..., 0.7375562 ,
         0.78321464, 0.80696153],
        ...,
        [0.85926592, 0.32348906, 0.26023181, ..., 0.57495215,
         0.57895578, 0.9734552 ],
        [0.74965186, 0.15362471, 0.09399744, ..., 0.63007598,
         0.52883218, 0.3400593 ],
        [0.52114736, 0.66684345, 0.66271128, ..., 0.61525486,
         0.11085453, 0.65360104]],

       [[0.98861152, 0.65132234, 0.60530806, ..., 0.14763735,
         0.28845914, 0.14602228],
        [0.37210558, 0.36527761, 0.6027145 , ..., 0.22706933,
         0.75373878, 0.6517352 ],
        [0.61574044, 0.23122045, 0.47627466, ..., 0.49839158,
         0.80187763, 0.7349254 ],
        ...,
        [0.74599205, 0.58273766, 0.09852495, ..., 0.6208036 ,

In [7]:
xset['ndvi'] = ((xset.nir-xset.red)/(xset.nir+xset.red))

In [8]:
xset

<xarray.Dataset>
Dimensions:  (time: 6, x: 1667, y: 1667)
Coordinates:
  * time     (time) datetime64[ns] 2019-01-01 2019-01-02 ... 2019-01-06
Dimensions without coordinates: x, y
Data variables:
    blue     (time, y, x) float64 0.1586 0.7531 0.5985 ... 0.697 0.4095 0.2409
    red      (time, y, x) float64 0.4759 2.259 1.795 ... 2.091 1.229 0.7228
    green    (time, y, x) float64 0.6345 3.013 2.394 ... 2.788 1.638 0.9637
    nir      (time, y, x) float64 0.7931 3.766 2.992 4.87 ... 3.485 2.048 1.205
    ndvi     (time, y, x) float64 0.25 0.25 0.25 0.25 ... 0.25 0.25 0.25 0.25

In [9]:
xset.ndvi

<xarray.DataArray 'ndvi' (time: 6, y: 1667, x: 1667)>
array([[[0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        ...,
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25]],

       [[0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        ...,
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25]],

       [[0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        ...,
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25

In [10]:
xset_ndvi_mean_by_window = xset.ndvi.rolling(time=time_window).mean(keep_attrs=True, skipna=True).dropna('time')

In [11]:
xset_ndvi_mean_by_window

<xarray.DataArray (time: 5, y: 1667, x: 1667)>
array([[[0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        ...,
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25]],

       [[0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        ...,
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25]],

       [[0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        ...,
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25, 0.25],
        [0.25, 0.25, 0.25, ..., 0.25, 0.25,

## 1b Se utilizan los datos de la ruta:

`/LUSTRE/MADMEX/tasks/2019_tasks/generacion_datos_entrenamiento_cultivos/examples_source_data`

In [12]:
path = '/LUSTRE/MADMEX/tasks/2019_tasks/generacion_datos_entrenamiento_cultivos/examples_source_data/' 

nc_files = [f for f in glob.glob(path + "/*.nc", recursive=True)]

In [13]:
nc_files

['/LUSTRE/MADMEX/tasks/2019_tasks/generacion_datos_entrenamiento_cultivos/examples_source_data/LS5_espa_21_-19_19960312164217000000.nc',
 '/LUSTRE/MADMEX/tasks/2019_tasks/generacion_datos_entrenamiento_cultivos/examples_source_data/LS5_espa_21_-19_19960124163902000000.nc',
 '/LUSTRE/MADMEX/tasks/2019_tasks/generacion_datos_entrenamiento_cultivos/examples_source_data/LS5_espa_21_-19_19961123165617000000.nc',
 '/LUSTRE/MADMEX/tasks/2019_tasks/generacion_datos_entrenamiento_cultivos/examples_source_data/LS5_espa_21_-19_19951121163445000000.nc',
 '/LUSTRE/MADMEX/tasks/2019_tasks/generacion_datos_entrenamiento_cultivos/examples_source_data/LS5_espa_21_-19_19950206164648000000.nc',
 '/LUSTRE/MADMEX/tasks/2019_tasks/generacion_datos_entrenamiento_cultivos/examples_source_data/LS5_espa_21_-19_19950310164531000000.nc',
 '/LUSTRE/MADMEX/tasks/2019_tasks/generacion_datos_entrenamiento_cultivos/examples_source_data/LS5_espa_21_-19_19961107165532000000.nc']

Combine nc files

In [14]:
ds_combined = xr.merge([xr.open_dataset(nc_file) for nc_file in nc_files])

In [15]:
ds_combined

<xarray.Dataset>
Dimensions:   (time: 7, x: 1667, y: 1667)
Coordinates:
  * time      (time) datetime64[ns] 1995-02-06T16:46:48 ... 1996-11-23T16:56:17
  * y         (y) float64 1.527e+06 1.526e+06 1.526e+06 ... 1.477e+06 1.477e+06
  * x         (x) float64 2.027e+06 2.027e+06 2.027e+06 ... 2.077e+06 2.077e+06
Data variables:
    crs       int32 -2147483647
    blue      (time, y, x) float32 149.0 124.0 98.0 71.0 ... 356.0 284.0 211.0
    green     (time, y, x) float32 119.0 119.0 119.0 119.0 ... 503.0 452.0 352.0
    red       (time, y, x) float32 104.0 104.0 104.0 104.0 ... 525.0 444.0 402.0
    nir       (time, y, x) float32 237.0 237.0 237.0 ... 1921.0 1825.0 1921.0
    swir1     (time, y, x) float32 164.0 164.0 164.0 ... 1682.0 1549.0 1251.0
    swir2     (time, y, x) float32 33.0 82.0 33.0 33.0 ... 980.0 790.0 553.0
    pixel_qa  (time, y, x) float32 68.0 68.0 68.0 68.0 ... 66.0 66.0 66.0 66.0
    dataset   (time) object b'creation_dt: \'2019-07-28T23:14:28.657079\'\nextent:\n  c

In [16]:
ds_combined.time

<xarray.DataArray 'time' (time: 7)>
array(['1995-02-06T16:46:48.000000000', '1995-03-10T16:45:31.000000000',
       '1995-11-21T16:34:45.000000000', '1996-01-24T16:39:02.000000000',
       '1996-03-12T16:42:17.000000000', '1996-11-07T16:55:32.000000000',
       '1996-11-23T16:56:17.000000000'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1995-02-06T16:46:48 ... 1996-11-23T16:56:17
Attributes:
    standard_name:  time
    long_name:      Time, unix time-stamp
    axis:           T

In [17]:
ds_combined.blue.attrs

OrderedDict([('grid_mapping', 'crs'),
             ('units', 'reflectance'),
             ('long_name', 'Surface Reflectance 0.45-0.52 microns (Blue)'),
             ('alias', 'band_1')])

In [18]:
ds_combined.blue

<xarray.DataArray 'blue' (time: 7, y: 1667, x: 1667)>
array([[[149., 124.,  98., ..., 374., 349., 248.],
        [124., 124., 124., ..., 425., 374., 273.],
        [ 98.,  98.,  98., ..., 425., 374., 324.],
        ...,
        [293., 345., 345., ..., 251., 276., 376.],
        [267., 267., 319., ..., 276., 276., 251.],
        [293., 319., 319., ..., 301., 226., 201.]],

       [[166., 144., 166., ..., 380., 318., 318.],
        [187., 144., 187., ..., 443., 401., 339.],
        [166., 144., 166., ..., 443., 422., 339.],
        ...,
        [163., 120., 204., ..., 257., 278., 527.],
        [121.,  99., 161., ..., 299., 278., 216.],
        [142., 120., 140., ..., 278., 216., 237.]],

       [[ 48.,  75., 128., ..., 357., 306., 280.],
        [102., 102., 102., ..., 409., 332., 332.],
        [102., 102., 102., ..., 435., 357., 280.],
        ...,
        [ 87.,  35., 114., ..., 281., 281., 483.],
        [ 62.,  87.,  87., ..., 255., 281., 230.],
        [ 35.,  87.,  87., ..., 255.

In [19]:
ds_combined.blue.isel(time=3).values

array([[133., 133.,  18., ..., 211., 211., 154.],
       [ 75.,  47.,  75., ..., 211., 209., 154.],
       [133., 105.,  75., ..., 182., 182., 209.],
       ...,
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan],
       [ nan,  nan,  nan, ...,  nan,  nan,  nan]], dtype=float32)

## 2 Calcular ndvi por ventana de tiempos para cada banda

In [20]:
time_window = 2

In [21]:
#ejemplo de cálculo de promedio en ventana de tiempo definida con time_window
ds_combined.blue.rolling(time=time_window).mean(keep_attrs=True, skipna=True).dropna('time')

<xarray.DataArray (time: 4, y: 1667, x: 1667)>
array([[[157.5, 134. , 132. , ..., 377. , 333.5, 283. ],
        [155.5, 134. , 155.5, ..., 434. , 387.5, 306. ],
        [132. , 121. , 132. , ..., 434. , 398. , 331.5],
        ...,
        [228. , 232.5, 274.5, ..., 254. , 277. , 451.5],
        [194. , 183. , 240. , ..., 287.5, 277. , 233.5],
        [217.5, 219.5, 229.5, ..., 289.5, 221. , 219. ]],

       [[107. , 109.5, 147. , ..., 368.5, 312. , 299. ],
        [144.5, 123. , 144.5, ..., 426. , 366.5, 335.5],
        [134. , 123. , 134. , ..., 439. , 389.5, 309.5],
        ...,
        [125. ,  77.5, 159. , ..., 269. , 279.5, 505. ],
        [ 91.5,  93. , 124. , ..., 277. , 279.5, 223. ],
        [ 88.5, 103.5, 113.5, ..., 266.5, 235.5, 220.5]],

       [[220. , 196. , 195.5, ..., 474.5, 443.5, 378.5],
        [229.5, 173.5, 129. , ..., 507.5, 446. , 423.5],
        [195. , 185. , 163.5, ..., 498. , 466.5, 433. ],
        ...,
        [141. , 109. , 173.5, ..., 284. , 369. , 506. ]

In [22]:
ds_combined['ndvi'] = ((ds_combined.nir-ds_combined.red)/(ds_combined.nir+ds_combined.red))

In [23]:
ds_combined

<xarray.Dataset>
Dimensions:   (time: 7, x: 1667, y: 1667)
Coordinates:
  * time      (time) datetime64[ns] 1995-02-06T16:46:48 ... 1996-11-23T16:56:17
  * y         (y) float64 1.527e+06 1.526e+06 1.526e+06 ... 1.477e+06 1.477e+06
  * x         (x) float64 2.027e+06 2.027e+06 2.027e+06 ... 2.077e+06 2.077e+06
Data variables:
    crs       int32 -2147483647
    blue      (time, y, x) float32 149.0 124.0 98.0 71.0 ... 356.0 284.0 211.0
    green     (time, y, x) float32 119.0 119.0 119.0 119.0 ... 503.0 452.0 352.0
    red       (time, y, x) float32 104.0 104.0 104.0 104.0 ... 525.0 444.0 402.0
    nir       (time, y, x) float32 237.0 237.0 237.0 ... 1921.0 1825.0 1921.0
    swir1     (time, y, x) float32 164.0 164.0 164.0 ... 1682.0 1549.0 1251.0
    swir2     (time, y, x) float32 33.0 82.0 33.0 33.0 ... 980.0 790.0 553.0
    pixel_qa  (time, y, x) float32 68.0 68.0 68.0 68.0 ... 66.0 66.0 66.0 66.0
    dataset   (time) object b'creation_dt: \'2019-07-28T23:14:28.657079\'\nextent:\n  c

In [24]:
ds_combined.ndvi

<xarray.DataArray 'ndvi' (time: 7, y: 1667, x: 1667)>
array([[[0.3900293 , 0.3900293 , 0.3900293 , ..., 0.5306186 ,
         0.5935275 , 0.6238291 ],
        [0.3900293 , 0.32258064, 0.4680307 , ..., 0.49166918,
         0.5787488 , 0.59113115],
        [0.4680307 , 0.4680307 , 0.32258064, ..., 0.50374067,
         0.5365616 , 0.59113115],
        ...,
        [0.5963396 , 0.50141966, 0.5618182 , ..., 0.6130398 ,
         0.61803955, 0.5063291 ],
        [0.59348536, 0.62945366, 0.60595536, ..., 0.5670282 ,
         0.5580271 , 0.62317383],
        [0.53594774, 0.6401419 , 0.61908895, ..., 0.5762208 ,
         0.578024  , 0.72328246]],

       [[0.47985348, 0.21929824, 0.38528138, ..., 0.49164525,
         0.54932505, 0.5692308 ],
        [0.38831615, 0.44791666, 0.5023474 , ..., 0.4679549 ,
         0.5051405 , 0.5478599 ],
        [0.21929824, 0.32380953, 0.32380953, ..., 0.48730105,
         0.50982493, 0.5478599 ],
        ...,
        [0.6556578 , 0.6481597 , 0.6191875 , ..., 0.61

In [25]:
da_combined_ndvi_mean_by_window = ds_combined.ndvi.rolling(time=time_window,center=True).mean()

In [26]:
da_combined_ndvi_mean_by_window

<xarray.DataArray (time: 7, y: 1667, x: 1667)>
array([[[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        ...,
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan]],

       [[0.4349414 , 0.30466378, 0.38765535, ..., 0.51113194,
         0.5714263 , 0.59652996],
        [0.38917273, 0.38524866, 0.48518905, ..., 0.47981203,
         0.5419446 , 0.56949556],
        [0.34366447, 0.3959201 , 0.3231951 , ..., 0.49552086,
         0.52319324, 0.56949556],
        ...,
        [0.62599874, 0.57478964, 0.59050286, ..., 0.6132083 ,

In [27]:
ds_combined.time.values

array(['1995-02-06T16:46:48.000000000', '1995-03-10T16:45:31.000000000',
       '1995-11-21T16:34:45.000000000', '1996-01-24T16:39:02.000000000',
       '1996-03-12T16:42:17.000000000', '1996-11-07T16:55:32.000000000',
       '1996-11-23T16:56:17.000000000'], dtype='datetime64[ns]')

In [28]:
times=np.datetime_as_string(da_combined_ndvi_mean_by_window.time.values,unit='D')

In [29]:
times

array(['1995-02-06', '1995-03-10', '1995-11-21', '1996-01-24',
       '1996-03-12', '1996-11-07', '1996-11-23'], dtype='<U28')

In [30]:
times=[datetime.strptime(x,'%Y-%m-%d') for x in times]

In [31]:
times

[datetime.datetime(1995, 2, 6, 0, 0),
 datetime.datetime(1995, 3, 10, 0, 0),
 datetime.datetime(1995, 11, 21, 0, 0),
 datetime.datetime(1996, 1, 24, 0, 0),
 datetime.datetime(1996, 3, 12, 0, 0),
 datetime.datetime(1996, 11, 7, 0, 0),
 datetime.datetime(1996, 11, 23, 0, 0)]

In [32]:
da_combined_ndvi_mean_by_window.name = 'ndvi_window_mean'

In [33]:
da_combined_ndvi_mean_by_window.assign_coords({'time':times}).to_series()

time        y          x        
1995-02-06  1526525.0  2027385.0         NaN
                       2027415.0         NaN
                       2027445.0         NaN
                       2027475.0         NaN
                       2027505.0         NaN
                                      ...   
1996-11-23  1476545.0  2077245.0    0.535197
                       2077275.0    0.517067
                       2077305.0    0.548726
                       2077335.0    0.617327
                       2077365.0    0.663434
Name: ndvi_window_mean, Length: 19452223, dtype: float32

In [34]:
dseries=da_combined_ndvi_mean_by_window.assign_coords({'time':times}).to_series()

In [35]:
dseries

time        y          x        
1995-02-06  1526525.0  2027385.0         NaN
                       2027415.0         NaN
                       2027445.0         NaN
                       2027475.0         NaN
                       2027505.0         NaN
                                      ...   
1996-11-23  1476545.0  2077245.0    0.535197
                       2077275.0    0.517067
                       2077305.0    0.548726
                       2077335.0    0.617327
                       2077365.0    0.663434
Name: ndvi_window_mean, Length: 19452223, dtype: float32

In [36]:
dseries.dropna()

time        y          x        
1995-03-10  1526525.0  2027385.0    0.434941
                       2027415.0    0.304664
                       2027445.0    0.387655
                       2027475.0    0.365385
                       2027505.0    0.305670
                                      ...   
1996-11-23  1476545.0  2077245.0    0.535197
                       2077275.0    0.517067
                       2077305.0    0.548726
                       2077335.0    0.617327
                       2077365.0    0.663434
Name: ndvi_window_mean, Length: 15176736, dtype: float32