# Preprocessing of rapideye: Top Of Atmosphere

# Example of one rapideye scene in LUSTRE:

`/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/`

Metadata in 2011-01-03T180703_RE5_3A-NAC_10114921_140489_metadata.xml

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/

```
total 326M
239M Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489.tif
 86M Mar  3  2015 2011-01-03T180703_RE5_3A-NAC_10114921_140489.tif.ovr
734K Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_browse.tif
 15K Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_license.txt
8.4K Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_metadata.xml
 586 Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_readme.txt
 13K Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/

```
total 322M
239M Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171.tif
 83M Mar  3  2015 2012-04-02T181815_RE2_3A-NAC_10853965_147171.tif.ovr
734K Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_browse.tif
 15K Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_license.txt
8.4K Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_metadata.xml
 586 Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_readme.txt
 13K Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2013/2013-02-18/l3a/

```
total 322M
239M Jul  8  2014 1450115_2013-02-18_RE5_3A_184276.tif
 83M Mar  3  2015 1450115_2013-02-18_RE5_3A_184276.tif.ovr
734K Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_browse.tif
 15K Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_license.txt
8.1K Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_metadata.xml
 532 Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_readme.txt
 13K Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2014/2014-02-12/l3a/

```
total 322M
239M Sep 30  2014 1450115_2014-02-12_RE2_3A_215717.tif
 83M Mar  3  2015 1450115_2014-02-12_RE2_3A_215717.tif.ovr
734K Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_browse.tif
 15K Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_license.txt
8.1K Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_metadata.xml
 532 Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_readme.txt
 13K Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2015/2015-03-30/l3a/

```
total 240M
239M Aug 11  2015 1450115_2015-03-30_RE4_3A_302419.tif
734K Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_browse.tif
 15K Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_license.txt
8.1K Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_metadata.xml
 532 Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_readme.txt
 13K Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2016/2016-03-07/l3a/

```
total 240M
239M Apr  8  2016 1450115_2016-03-07_RE4_3A_359857.tif
734K Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_browse.tif
 16K Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_license.txt
8.1K Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_metadata.xml
 532 Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_readme.txt
 13K Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_udm.tif
```


For TOA's we need to get some information from metadata

In [1]:
import os
import re
import datetime
from glob import glob
import xml.etree.ElementTree as ET

In [2]:
#path = '/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/'
path = '/LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/'

In [3]:
xml_file_list = glob(os.path.join(path, '*.xml'))

In [4]:
xml_file_list

['/LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/2012-04-02T181815_RE2_3A-NAC_10853965_147171_metadata.xml']

In [5]:
pattern = re.compile(r'.*[0-9]{4}-[0-9]{2}-[0-9]{2}.*_RE(2|4|5)_3A.*_metadata\.xml')

In [6]:
xml_file_list = [x for x in xml_file_list if pattern.search(x)]

In [7]:
xml_file_list

['/LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/2012-04-02T181815_RE2_3A-NAC_10853965_147171_metadata.xml']

In [8]:
if len(xml_file_list) != 1:
    raise ValueError('Could not identify a unique xml metadata file')
xml_file = xml_file_list[0]
# Start parsing xml

In [9]:
root = ET.parse(xml_file).getroot()

In [10]:
ns = 'http://www.opengis.net/gml'
ns2 = 'http://schemas.rapideye.de/products/productMetadataGeocorrected'
ns3 = 'http://earth.esa.int/eop'
ns4 = 'http://earth.esa.int/opt'

In [11]:
solar_zenith = float(root.find('ns:using/ns3:EarthObservationEquipment/ns3:acquisitionParameters/ns2:Acquisition/ns4:illuminationElevationAngle',
                               namespaces={'ns': ns, 'ns2': ns2, 'ns3':ns3, 'ns4':ns4}).text)

In [12]:
solar_zenith

70.79801

In [13]:
dt = root.find('ns:metaDataProperty/ns2:EarthObservationMetaData/ns3:downlinkedTo/ns3:DownlinkInformation/ns3:acquisitionDate',
          namespaces={'ns': ns, 'ns2': ns2, 'ns3': ns3}).text

In [14]:
dt_format = lambda x: datetime.datetime.strptime(x, "%Y-%m-%dT%H:%M:%S.%fZ")

In [15]:
dt_format(dt)

datetime.datetime(2012, 4, 2, 18, 18, 15, 672563)

In [16]:
dt = dt_format(dt)

In [17]:
#solar_azimuth = float(root.find('ns:using/ns3:EarthObservationEquipment/ns3:acquisitionParameters/ns2:Acquisition/ns4:illuminationAzimuthAngle',
#                         namespaces={'ns': ns, 'ns2': ns2, 'ns3':ns3, 'ns4':ns4}).text)

In [18]:
#solar_azimuth

# TOA's calculation

Auxiliar functions

Missing dependency: `ephem` install it via: `pip3.6 install --user ephem`

In [17]:
import ephem

In [18]:
def calculate_distance_sun_earth(datestr):
    '''
    Calculates distance between sun and earth in astronomical unints for a given
    date. Date needs to be a string using format YYYY-MM-DD or datetime object
    from metadata.
    '''
    sun = ephem.Sun()  # @UndefinedVariable
    if isinstance(datestr, str):
        sun.compute(datetime.datetime.strptime(datestr, '%Y-%m-%d').date())
    elif isinstance(datestr, datetime.datetime):
        sun.compute(datestr)
    sun_distance = sun.earth_distance  # needs to be between 0.9832898912 AU and 1.0167103335 AU
    return sun_distance

In [19]:
calculate_distance_sun_earth(dt)

0.9997721314430237

Function for Radiances

In [20]:
import rasterio

In [21]:
tif_file_list = glob(os.path.join(path, '*.tif'))

In [22]:
tif_file_list

['/LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/2012-04-02T181815_RE2_3A-NAC_10853965_147171.tif',
 '/LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/2012-04-02T181815_RE2_3A-NAC_10853965_147171_browse.tif',
 '/LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/2012-04-02T181815_RE2_3A-NAC_10853965_147171_udm.tif']

In [23]:
pattern = re.compile(r'.*[0-9]{4}-[0-9]{2}-[0-9]{2}.*_RE(2|4|5)_3A.*[0-9]{6}\.tif$')

In [24]:
tif_file_list = [x for x in tif_file_list if pattern.search(x)]

In [25]:
tif_file_list

['/LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/2012-04-02T181815_RE2_3A-NAC_10853965_147171.tif']

In [28]:
if len(tif_file_list) != 1:
    raise ValueError('Could not identify a unique tif file')
tif_file = tif_file_list[0]

In [29]:
with rasterio.open(tif_file) as src:
    data = src.read()
    meta_src = src.meta.copy()

In [30]:
data

array([[[ 8170,  8240,  8559, ...,  7550,  7506,  7558],
        [ 8383,  8484,  8743, ...,  7822,  7822,  8197],
        [ 8414,  8393,  8499, ...,  8139,  8549,  8197],
        ...,
        [ 6651,  6641,  6542, ..., 10842, 10409, 10409],
        [ 6641,  6641,  6667, ..., 10552, 10537, 10514],
        [ 6767,  6767,  6853, ..., 10359, 10537, 10514]],

       [[ 7789,  7904,  8094, ...,  6348,  6227,  6227],
        [ 7874,  8076,  8208, ...,  6557,  6649,  7051],
        [ 7989,  7989,  7950, ...,  6827,  7824,  7501],
        ...,
        [ 5580,  5599,  5599, ...,  9624,  9447,  9447],
        [ 5666,  5599,  5645, ...,  9714,  9631,  9631],
        [ 5666,  5686,  5703, ...,  9653,  9630,  9497]],

       [[ 6935,  6935,  6654, ...,  4918,  4918,  4864],
        [ 6935,  7250,  7250, ...,  5488,  4864,  4864],
        [ 6849,  7137,  7137, ...,  5488,  6082,  6036],
        ...,
        [ 3739,  4087,  4087, ...,  5597,  5367,  5374],
        [ 3767,  3973,  3955, ...,  5539,  55

In [31]:
meta_src

{'driver': 'GTiff',
 'dtype': 'uint16',
 'nodata': None,
 'width': 5000,
 'height': 5000,
 'count': 5,
 'crs': CRS.from_epsg(32614),
 'transform': Affine(5.0, 0.0, 499500.0,
        0.0, -5.0, 2664500.0)}

In [32]:
def calculate_rad_rapideye(data, radiometricScaleFactor=0.009999999776482582, radiometricOffsetValue=0.0):
    '''
    Convert digital number into radiance according to rapideye documentation. Returns 
    sensor radiance of that pixel in watts per steradian per square meter.
    '''
    rad = data * radiometricScaleFactor + radiometricOffsetValue
    rad[rad == radiometricOffsetValue] = 0
    return rad

In [33]:
rad_data = calculate_rad_rapideye(data)

In [34]:
rad_data

array([[[ 81.69999817,  82.39999816,  85.58999809, ...,  75.49999831,
          75.05999832,  75.57999831],
        [ 83.82999813,  84.8399981 ,  87.42999805, ...,  78.21999825,
          78.21999825,  81.96999817],
        [ 84.13999812,  83.92999812,  84.9899981 , ...,  81.38999818,
          85.48999809,  81.96999817],
        ...,
        [ 66.50999851,  66.40999852,  65.41999854, ..., 108.41999758,
         104.08999767, 104.08999767],
        [ 66.40999852,  66.40999852,  66.66999851, ..., 105.51999764,
         105.36999764, 105.13999765],
        [ 67.66999849,  67.66999849,  68.52999847, ..., 103.58999768,
         105.36999764, 105.13999765]],

       [[ 77.88999826,  79.03999823,  80.93999819, ...,  63.47999858,
          62.26999861,  62.26999861],
        [ 78.73999824,  80.75999819,  82.07999817, ...,  65.56999853,
          66.48999851,  70.50999842],
        [ 79.88999821,  79.88999821,  79.49999822, ...,  68.26999847,
          78.23999825,  75.00999832],
        ...,


Function for TOA's

In [35]:
import numpy as np

In [36]:
def calculate_toa_rapideye(rad, sun_distance, sun_elevation):
    '''
    Calculates top of atmosphere from radiance according to RE documentation
    needs sun-earth distance and sun elevation.
    '''
    bands = 5
    solar_zenit = 90 - sun_elevation
    irradiance = [1997.8, 1863.5, 1560.4, 1395.0, 1124.4]  # Exo-Atmospheric Irradiance 
    toa = rad
    for i in range(bands):
        toa[i, :, :] = rad[i, :, :] * (np.pi * (sun_distance * sun_distance)) / (irradiance[i] * np.cos(np.pi * solar_zenit / 180)) 
    return toa

In [37]:
sun_earth_distance = calculate_distance_sun_earth(dt)
top_of_atmosphere_data = calculate_toa_rapideye(rad_data, sun_earth_distance, solar_zenith)

In [38]:
top_of_atmosphere_data

array([[[0.13598221, 0.1371473 , 0.14245676, ..., 0.12566288,
         0.12493054, 0.12579603],
        [0.1395274 , 0.14120846, 0.14551928, ..., 0.13019007,
         0.13019007, 0.1364316 ],
        [0.14004337, 0.13969385, 0.14145812, ..., 0.13546625,
         0.14229032, 0.1364316 ],
        ...,
        [0.11069984, 0.1105334 , 0.10888564, ..., 0.18045522,
         0.17324833, 0.17324833],
        [0.1105334 , 0.1105334 , 0.11096615, ..., 0.17562843,
         0.17537877, 0.17499596],
        [0.11263056, 0.11263056, 0.11406195, ..., 0.17241613,
         0.17537877, 0.17499596]],

       [[0.13898386, 0.14103587, 0.14442616, ..., 0.11327122,
         0.11111214, 0.11111214],
        [0.14050057, 0.14410497, 0.14646033, ..., 0.11700053,
         0.11864215, 0.12581528],
        [0.14255258, 0.14255258, 0.14185668, ..., 0.12181831,
         0.13960838, 0.1338449 ],
        ...,
        [0.09956733, 0.09990636, 0.09990636, ..., 0.17172688,
         0.16856856, 0.16856856],
        [0.1

In [39]:
meta_src

{'driver': 'GTiff',
 'dtype': 'uint16',
 'nodata': None,
 'width': 5000,
 'height': 5000,
 'count': 5,
 'crs': CRS.from_epsg(32614),
 'transform': Affine(5.0, 0.0, 499500.0,
        0.0, -5.0, 2664500.0)}

In [40]:
meta = meta_src

In [41]:
meta.update(compress='lzw',
            dtype=rasterio.float64)

In [42]:
meta

{'driver': 'GTiff',
 'dtype': 'float64',
 'nodata': None,
 'width': 5000,
 'height': 5000,
 'count': 5,
 'crs': CRS.from_epsg(32614),
 'transform': Affine(5.0, 0.0, 499500.0,
        0.0, -5.0, 2664500.0),
 'compress': 'lzw'}

In [43]:
tif_file

'/LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/2012-04-02T181815_RE2_3A-NAC_10853965_147171.tif'

In [44]:
filename_result = os.path.splitext(os.path.basename(tif_file))[0] + '_toa' + '.tif'

In [45]:
filename_result

'2012-04-02T181815_RE2_3A-NAC_10853965_147171_toa.tif'

In [46]:
filename_path_result = os.path.expanduser(os.path.join("~/", filename_result))

In [47]:
filename_path_result

'/home/madmex_user/2012-04-02T181815_RE2_3A-NAC_10853965_147171_toa.tif'

In [48]:
with rasterio.open(filename_path_result, "w", **meta) as dst:
    dst.write(top_of_atmosphere_data)