# Preprocessing of rapideye: Top Of Atmosphere

# Example of one rapideye scene in LUSTRE:

`/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/`

Metadata in 2011-01-03T180703_RE5_3A-NAC_10114921_140489_metadata.xml

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/

```
total 326M
239M Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489.tif
 86M Mar  3  2015 2011-01-03T180703_RE5_3A-NAC_10114921_140489.tif.ovr
734K Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_browse.tif
 15K Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_license.txt
8.4K Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_metadata.xml
 586 Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_readme.txt
 13K Mar 11  2014 2011-01-03T180703_RE5_3A-NAC_10114921_140489_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2012/2012-04-02/l3a/

```
total 322M
239M Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171.tif
 83M Mar  3  2015 2012-04-02T181815_RE2_3A-NAC_10853965_147171.tif.ovr
734K Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_browse.tif
 15K Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_license.txt
8.4K Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_metadata.xml
 586 Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_readme.txt
 13K Mar 12  2014 2012-04-02T181815_RE2_3A-NAC_10853965_147171_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2013/2013-02-18/l3a/

```
total 322M
239M Jul  8  2014 1450115_2013-02-18_RE5_3A_184276.tif
 83M Mar  3  2015 1450115_2013-02-18_RE5_3A_184276.tif.ovr
734K Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_browse.tif
 15K Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_license.txt
8.1K Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_metadata.xml
 532 Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_readme.txt
 13K Jul  8  2014 1450115_2013-02-18_RE5_3A_184276_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2014/2014-02-12/l3a/

```
total 322M
239M Sep 30  2014 1450115_2014-02-12_RE2_3A_215717.tif
 83M Mar  3  2015 1450115_2014-02-12_RE2_3A_215717.tif.ovr
734K Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_browse.tif
 15K Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_license.txt
8.1K Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_metadata.xml
 532 Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_readme.txt
 13K Sep 30  2014 1450115_2014-02-12_RE2_3A_215717_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2015/2015-03-30/l3a/

```
total 240M
239M Aug 11  2015 1450115_2015-03-30_RE4_3A_302419.tif
734K Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_browse.tif
 15K Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_license.txt
8.1K Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_metadata.xml
 532 Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_readme.txt
 13K Aug 11  2015 1450115_2015-03-30_RE4_3A_302419_udm.tif
```

ls -lh /LUSTRE/MADMEX/eodata/rapideye/1450115/2016/2016-03-07/l3a/

```
total 240M
239M Apr  8  2016 1450115_2016-03-07_RE4_3A_359857.tif
734K Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_browse.tif
 16K Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_license.txt
8.1K Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_metadata.xml
 532 Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_readme.txt
 13K Apr  8  2016 1450115_2016-03-07_RE4_3A_359857_udm.tif
```


For TOA's we need to get some information from metadata

In [1]:
import os
import re
import datetime
from glob import glob
import xml.etree.ElementTree as ET


from rasterio.crs import CRS
from pyproj import Proj


In [2]:
path = '/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/'

In [3]:
xml_file_list = glob(os.path.join(path, '*.xml'))

In [4]:
xml_file_list

['/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/2011-01-03T180703_RE5_3A-NAC_10114921_140489_metadata.xml']

In [5]:
pattern = re.compile(r'.*[0-9]{4}-[0-9]{2}-[0-9]{2}.*_RE(2|4|5)_3A.*_metadata\.xml')

In [6]:
xml_file_list = [x for x in xml_file_list if pattern.search(x)]

In [7]:
xml_file_list

['/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/2011-01-03T180703_RE5_3A-NAC_10114921_140489_metadata.xml']

In [8]:
if len(xml_file_list) != 1:
    raise ValueError('Could not identify a unique xml metadata file')
xml_file = xml_file_list[0]
# Start parsing xml

In [9]:
root = ET.parse(xml_file).getroot()

In [10]:
ns = 'http://www.opengis.net/gml'
ns2 = 'http://schemas.rapideye.de/products/productMetadataGeocorrected'
ns3 = 'http://earth.esa.int/eop'
ns4 = 'http://earth.esa.int/opt'

In [11]:
solar_zenith = float(root.find('ns:using/ns3:EarthObservationEquipment/ns3:acquisitionParameters/ns2:Acquisition/ns4:illuminationElevationAngle',
                               namespaces={'ns': ns, 'ns2': ns2, 'ns3':ns3, 'ns4':ns4}).text)

In [12]:
solar_zenith

42.67834

In [13]:
dt = root.find('ns:metaDataProperty/ns2:EarthObservationMetaData/ns3:downlinkedTo/ns3:DownlinkInformation/ns3:acquisitionDate',
          namespaces={'ns': ns, 'ns2': ns2, 'ns3': ns3}).text

In [14]:
dt_format = lambda x: datetime.datetime.strptime(x, "%Y-%m-%dT%H:%M:%S.%fZ")

In [15]:
dt_format(dt)

datetime.datetime(2011, 1, 3, 18, 7, 3, 649071)

In [16]:
dt = dt_format(dt)

In [17]:
#solar_azimuth = float(root.find('ns:using/ns3:EarthObservationEquipment/ns3:acquisitionParameters/ns2:Acquisition/ns4:illuminationAzimuthAngle',
#                         namespaces={'ns': ns, 'ns2': ns2, 'ns3':ns3, 'ns4':ns4}).text)

In [18]:
#solar_azimuth

# TOA's calculation

Auxiliar functions

Missing dependency: `ephem` install it via: `pip3.6 install --user ephem`

In [19]:
import ephem

In [20]:
def calculate_distance_sun_earth(datestr):
    '''
    Calculates distance between sun and earth in astronomical unints for a given
    date. Date needs to be a string using format YYYY-MM-DD or datetime object
    from metadata.
    '''
    sun = ephem.Sun()  # @UndefinedVariable
    if isinstance(datestr, str):
        sun.compute(datetime.datetime.strptime(datestr, '%Y-%m-%d').date())
    elif isinstance(datestr, datetime.datetime):
        sun.compute(datestr)
    sun_distance = sun.earth_distance  # needs to be between 0.9832898912 AU and 1.0167103335 AU
    return sun_distance

In [21]:
calculate_distance_sun_earth(dt)

0.9833409786224365

Function for Radiances

In [22]:
import rasterio

In [23]:
tif_file_list = glob(os.path.join(path, '*.tif'))

In [24]:
tif_file_list

['/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/2011-01-03T180703_RE5_3A-NAC_10114921_140489_browse.tif',
 '/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/2011-01-03T180703_RE5_3A-NAC_10114921_140489.tif',
 '/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/2011-01-03T180703_RE5_3A-NAC_10114921_140489_udm.tif']

In [25]:
pattern = re.compile(r'.*[0-9]{4}-[0-9]{2}-[0-9]{2}.*_RE(2|4|5)_3A.*[0-9]{6}\.tif$')

In [26]:
tif_file_list = [x for x in tif_file_list if pattern.search(x)]

In [27]:
tif_file_list

['/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/2011-01-03T180703_RE5_3A-NAC_10114921_140489.tif']

In [28]:
if len(tif_file_list) != 1:
    raise ValueError('Could not identify a unique xml metadata file')
tif_file = tif_file_list[0]

In [29]:
with rasterio.open(tif_file) as src:
    data = src.read()
    meta_src = src.meta.copy()

In [30]:
data

array([[[7517, 7517, 7495, ..., 6067, 5661, 5714],
        [7325, 7209, 7209, ..., 6067, 5899, 6000],
        [7206, 7209, 7209, ..., 5923, 5923, 6501],
        ...,
        [4683, 4712, 4617, ..., 5197, 5339, 5319],
        [4898, 4807, 4665, ..., 5222, 5222, 5178],
        [4921, 4807, 4665, ..., 5291, 5248, 5248]],

       [[7102, 7102, 7123, ..., 4547, 4547, 4797],
        [7125, 7076, 7076, ..., 4644, 4644, 5038],
        [7125, 7147, 7147, ..., 4741, 5208, 5208],
        ...,
        [3715, 3815, 3809, ..., 4179, 4243, 4005],
        [3768, 3768, 3690, ..., 4179, 4243, 4006],
        [3673, 3618, 3618, ..., 4030, 4030, 4146]],

       [[7244, 7244, 7102, ..., 3732, 3724, 3724],
        [7267, 7267, 7102, ..., 3618, 3724, 4436],
        [7267, 7125, 7125, ..., 3435, 3724, 4436],
        ...,
        [2366, 2645, 2494, ..., 2205, 2205, 2166],
        [2600, 2600, 2562, ..., 2205, 2120, 2120],
        [2577, 2577, 2562, ..., 2136, 2097, 2097]],

       [[5973, 6034, 6017, ..., 3592,

In [31]:
meta_src

{'driver': 'GTiff',
 'dtype': 'uint16',
 'nodata': None,
 'width': 5000,
 'height': 5000,
 'count': 5,
 'crs': CRS.from_epsg(32614),
 'transform': Affine(5.0, 0.0, 499500.0,
        0.0, -5.0, 2664500.0)}

In [32]:
def calculate_rad_rapideye(data, radiometricScaleFactor=0.009999999776482582, radiometricOffsetValue=0.0):
    '''
    Convert digital number into radiance according to rapideye documentation. Returns 
    sensor radiance of that pixel in watts per steradian per square meter.
    '''
    rad = data * radiometricScaleFactor + radiometricOffsetValue
    rad[rad == radiometricOffsetValue] = 0
    return rad

In [33]:
rad_data = calculate_rad_rapideye(data)

In [34]:
rad_data

array([[[75.16999832, 75.16999832, 74.94999832, ..., 60.66999864,
         56.60999873, 57.13999872],
        [73.24999836, 72.08999839, 72.08999839, ..., 60.66999864,
         58.98999868, 59.99999866],
        [72.05999839, 72.08999839, 72.08999839, ..., 59.22999868,
         59.22999868, 65.00999855],
        ...,
        [46.82999895, 47.11999895, 46.16999897, ..., 51.96999884,
         53.38999881, 53.18999881],
        [48.97999891, 48.06999893, 46.64999896, ..., 52.21999883,
         52.21999883, 51.77999884],
        [49.2099989 , 48.06999893, 46.64999896, ..., 52.90999882,
         52.47999883, 52.47999883]],

       [[71.01999841, 71.01999841, 71.22999841, ..., 45.46999898,
         45.46999898, 47.96999893],
        [71.24999841, 70.75999842, 70.75999842, ..., 46.43999896,
         46.43999896, 50.37999887],
        [71.24999841, 71.4699984 , 71.4699984 , ..., 47.40999894,
         52.07999884, 52.07999884],
        ...,
        [37.14999917, 38.14999915, 38.08999915, ..., 4

Function for TOA's

In [35]:
import numpy as np

In [36]:
def calculate_toa_rapideye(rad, sun_distance, sun_elevation):
    '''
    Calculates top of atmosphere from radiance according to RE documentation
    needs sun-earth distance and sun elevation.
    '''
    bands = 5
    solar_zenit = 90 - sun_elevation
    irradiance = [1997.8, 1863.5, 1560.4, 1395.0, 1124.4]  # Exo-Atmospheric Irradiance 
    toa = rad
    for i in range(bands):
        toa[i, :, :] = rad[i, :, :] * (np.pi * (sun_distance * sun_distance)) / (irradiance[i] * np.cos(np.pi * solar_zenit / 180)) 
    return toa

In [37]:
sun_earth_distance = calculate_distance_sun_earth(dt)
top_of_atmosphere_data = calculate_toa_rapideye(rad_data, sun_earth_distance, solar_zenith)

In [38]:
top_of_atmosphere_data

array([[[0.16861519, 0.16861519, 0.16812171, ..., 0.13608998,
         0.12698292, 0.12817177],
        [0.16430841, 0.16170639, 0.16170639, ..., 0.13608998,
         0.13232154, 0.13458709],
        [0.1616391 , 0.16170639, 0.16170639, ..., 0.13285989,
         0.13285989, 0.14582511],
        ...,
        [0.10504523, 0.10569573, 0.10356477, ..., 0.11657485,
         0.11976008, 0.11931146],
        [0.10986793, 0.10782669, 0.10464146, ..., 0.11713563,
         0.11713563, 0.11614866],
        [0.11038385, 0.10782669, 0.10464146, ..., 0.11868338,
         0.11771884, 0.11771884]],

       [[0.17078725, 0.17078725, 0.17129225, ..., 0.1093452 ,
         0.1093452 , 0.11535714],
        [0.17134035, 0.17016201, 0.17016201, ..., 0.11167783,
         0.11167783, 0.12115265],
        [0.17134035, 0.1718694 , 0.1718694 , ..., 0.11401047,
         0.12524077, 0.12524077],
        ...,
        [0.08933746, 0.09174223, 0.09159795, ..., 0.10049562,
         0.10203468, 0.09631131],
        [0.0

In [39]:
meta_src

{'driver': 'GTiff',
 'dtype': 'uint16',
 'nodata': None,
 'width': 5000,
 'height': 5000,
 'count': 5,
 'crs': CRS.from_epsg(32614),
 'transform': Affine(5.0, 0.0, 499500.0,
        0.0, -5.0, 2664500.0)}

In [40]:
meta = meta_src

In [41]:
meta.update(compress='lzw',
            dtype=rasterio.float64)

In [42]:
meta

{'driver': 'GTiff',
 'dtype': 'float64',
 'nodata': None,
 'width': 5000,
 'height': 5000,
 'count': 5,
 'crs': CRS.from_epsg(32614),
 'transform': Affine(5.0, 0.0, 499500.0,
        0.0, -5.0, 2664500.0),
 'compress': 'lzw'}

In [43]:
tif_file

'/LUSTRE/MADMEX/eodata/rapideye/1450115/2011/2011-01-03/l3a/2011-01-03T180703_RE5_3A-NAC_10114921_140489.tif'

In [47]:
filename_result = os.path.splitext(os.path.basename(tif_file))[0] + '_toa' + '.tif'

In [48]:
filename_result

'2011-01-03T180703_RE5_3A-NAC_10114921_140489_toa.tif'

In [49]:
filename_path_result = os.path.expanduser(os.path.join("~/", filename_result))

In [50]:
filename_path_result

'/home/madmex_user/2011-01-03T180703_RE5_3A-NAC_10114921_140489_toa.tif'

In [51]:
with rasterio.open(filename_path_result, "w", **meta) as dst:
    dst.write(top_of_atmosphere_data)